# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'odev1.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1424, 903)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidgetOdev2 = QtWidgets.QTabWidget(Form)
        self.tabWidgetOdev2.setObjectName("tabWidgetOdev2")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.layoutWidget = QtWidgets.QWidget(self.tab_3)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 340, 721, 311))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEditImagePath = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEditImagePath.setObjectName("lineEditImagePath")
        self.horizontalLayout.addWidget(self.lineEditImagePath)
        self.loadImageButton = QtWidgets.QPushButton(self.layoutWidget)
        self.loadImageButton.setObjectName("loadImageButton")
        self.horizontalLayout.addWidget(self.loadImageButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.HistogramButton = QtWidgets.QPushButton(self.layoutWidget)
        self.HistogramButton.setObjectName("HistogramButton")
        self.gridLayout.addWidget(self.HistogramButton, 1, 2, 1, 1)
        self.GrayscaleConverterButton = QtWidgets.QPushButton(self.layoutWidget)
        self.GrayscaleConverterButton.setObjectName("GrayscaleConverterButton")
        self.gridLayout.addWidget(self.GrayscaleConverterButton, 0, 2, 1, 1)
        self.BlurAddButton = QtWidgets.QPushButton(self.layoutWidget)
        self.BlurAddButton.setObjectName("BlurAddButton")
        self.gridLayout.addWidget(self.BlurAddButton, 1, 0, 1, 1)
        self.RgbConverterButton = QtWidgets.QPushButton(self.layoutWidget)
        self.RgbConverterButton.setObjectName("RgbConverterButton")
        self.gridLayout.addWidget(self.RgbConverterButton, 0, 0, 1, 1)
        self.EdgeDetectButton = QtWidgets.QPushButton(self.layoutWidget)
        self.EdgeDetectButton.setObjectName("EdgeDetectButton")
        self.gridLayout.addWidget(self.EdgeDetectButton, 1, 1, 1, 1)
        self.HSVConverterButton = QtWidgets.QPushButton(self.layoutWidget)
        self.HSVConverterButton.setObjectName("HSVConverterButton")
        self.gridLayout.addWidget(self.HSVConverterButton, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.ProcessedImageButton = QtWidgets.QLabel(self.tab_3)
        self.ProcessedImageButton.setGeometry(QtCore.QRect(10, 17, 721, 317))
        self.ProcessedImageButton.setObjectName("ProcessedImageButton")
        self.formLayoutWidget = QtWidgets.QWidget(self.tab_3)
        self.formLayoutWidget.setGeometry(QtCore.QRect(20, 670, 341, 71))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.buyutmeLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.buyutmeLineEdit.setObjectName("buyutmeLineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.buyutmeLineEdit)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.formLayout.setItem(1, QtWidgets.QFormLayout.LabelRole, spacerItem)
        self.buyut_PushButton = QtWidgets.QPushButton(self.formLayoutWidget)
        self.buyut_PushButton.setObjectName("buyut_PushButton")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.buyut_PushButton)
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.tab_3)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(20, 750, 341, 81))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_2.setObjectName("label_2")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.kucultmeLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.kucultmeLineEdit.setObjectName("kucultmeLineEdit")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.kucultmeLineEdit)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.formLayout_2.setItem(1, QtWidgets.QFormLayout.LabelRole, spacerItem1)
        self.kucult_PushButton = QtWidgets.QPushButton(self.formLayoutWidget_2)
        self.kucult_PushButton.setObjectName("kucult_PushButton")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.kucult_PushButton)
        self.formLayoutWidget_3 = QtWidgets.QWidget(self.tab_3)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(390, 670, 341, 71))
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.formLayout_3 = QtWidgets.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_3.setObjectName("label_3")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.DondurmeAcisiLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.DondurmeAcisiLineEdit.setObjectName("DondurmeAcisiLineEdit")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.DondurmeAcisiLineEdit)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.formLayout_3.setItem(1, QtWidgets.QFormLayout.LabelRole, spacerItem2)
        self.dondurPushButton = QtWidgets.QPushButton(self.formLayoutWidget_3)
        self.dondurPushButton.setObjectName("dondurPushButton")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.dondurPushButton)
        self.formLayoutWidget_4 = QtWidgets.QWidget(self.tab_3)
        self.formLayoutWidget_4.setGeometry(QtCore.QRect(390, 750, 341, 89))
        self.formLayoutWidget_4.setObjectName("formLayoutWidget_4")
        self.formLayout_4 = QtWidgets.QFormLayout(self.formLayoutWidget_4)
        self.formLayout_4.setContentsMargins(0, 0, 0, 0)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.label_4.setObjectName("label_4")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.zoomIn_PushButton_2 = QtWidgets.QPushButton(self.formLayoutWidget_4)
        self.zoomIn_PushButton_2.setObjectName("zoomIn_PushButton_2")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.zoomIn_PushButton_2)
        self.zoomOut_PushButton = QtWidgets.QPushButton(self.formLayoutWidget_4)
        self.zoomOut_PushButton.setObjectName("zoomOut_PushButton")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.zoomOut_PushButton)
        self.gridLayoutWidget = QtWidgets.QWidget(self.tab_3)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(740, 500, 661, 80))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.sinusSigmoid_PushButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.sinusSigmoid_PushButton.setObjectName("sinusSigmoid_PushButton")
        self.gridLayout_2.addWidget(self.sinusSigmoid_PushButton, 2, 1, 1, 1)
        self.steepSigmoid_PushButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.steepSigmoid_PushButton.setObjectName("steepSigmoid_PushButton")
        self.gridLayout_2.addWidget(self.steepSigmoid_PushButton, 2, 0, 1, 1)
        self.standartSigmoidPushButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.standartSigmoidPushButton.setObjectName("standartSigmoidPushButton")
        self.gridLayout_2.addWidget(self.standartSigmoidPushButton, 1, 0, 1, 1)
        self.shiftedSigmoid_PushButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.shiftedSigmoid_PushButton.setObjectName("shiftedSigmoid_PushButton")
        self.gridLayout_2.addWidget(self.shiftedSigmoid_PushButton, 1, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 0, 1, 2)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.tab_3)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(740, 600, 671, 71))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.DetectHumanEyePushButton = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.DetectHumanEyePushButton.setObjectName("DetectHumanEyePushButton")
        self.gridLayout_3.addWidget(self.DetectHumanEyePushButton, 1, 1, 1, 1)
        self.DetectLines_PushButton = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.DetectLines_PushButton.setObjectName("DetectLines_PushButton")
        self.gridLayout_3.addWidget(self.DetectLines_PushButton, 1, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 0, 0, 1, 2)
        self.NewImage = QtWidgets.QLabel(self.tab_3)
        self.NewImage.setGeometry(QtCore.QRect(750, 10, 621, 321))
        self.NewImage.setObjectName("NewImage")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.tab_3)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(740, 700, 671, 51))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_7.setObjectName("label_7")
        self.gridLayout_4.addWidget(self.label_7, 0, 0, 1, 2)
        self.DeblurringPushButton = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.DeblurringPushButton.setObjectName("DeblurringPushButton")
        self.gridLayout_4.addWidget(self.DeblurringPushButton, 1, 0, 1, 2)
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.tab_3)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(740, 780, 671, 51))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_8.setObjectName("label_8")
        self.gridLayout_5.addWidget(self.label_8, 0, 0, 1, 2)
        self.CountAndExtractButton = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.CountAndExtractButton.setObjectName("CountAndExtractButton")
        self.gridLayout_5.addWidget(self.CountAndExtractButton, 1, 0, 1, 2)
        self.tabWidgetOdev2.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tabWidgetOdev2.addTab(self.tab_4, "")
        self.verticalLayout_2.addWidget(self.tabWidgetOdev2)

        self.retranslateUi(Form)
        self.tabWidgetOdev2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "DijitalGörüntüİşleme_221229054_BüşraÖnal"))
        self.loadImageButton.setText(_translate("Form", "Load İmage"))
        self.HistogramButton.setText(_translate("Form", "Histogram"))
        self.GrayscaleConverterButton.setText(_translate("Form", "Grayscale"))
        self.BlurAddButton.setText(_translate("Form", "Blur"))
        self.RgbConverterButton.setText(_translate("Form", "RGB"))
        self.EdgeDetectButton.setText(_translate("Form", "Edge Detect"))
        self.HSVConverterButton.setText(_translate("Form", "HSV "))
        self.ProcessedImageButton.setText(_translate("Form", "ProcessedImage"))
        self.label.setText(_translate("Form", "Miktar :"))
        self.buyut_PushButton.setText(_translate("Form", "Büyüt "))
        self.label_2.setText(_translate("Form", "Miktar :"))
        self.kucult_PushButton.setText(_translate("Form", "Küçült"))
        self.label_3.setText(_translate("Form", "Açı :"))
        self.dondurPushButton.setText(_translate("Form", "Döndür"))
        self.label_4.setText(_translate("Form", "Boyut :"))
        self.zoomIn_PushButton_2.setText(_translate("Form", "Zoom In"))
        self.zoomOut_PushButton.setText(_translate("Form", "Zoom out"))
        self.sinusSigmoid_PushButton.setText(_translate("Form", "Sinus-S-Curve"))
        self.steepSigmoid_PushButton.setText(_translate("Form", "Steep Sigmoid"))
        self.standartSigmoidPushButton.setText(_translate("Form", "Standart Sigmoid"))
        self.shiftedSigmoid_PushButton.setText(_translate("Form", "Shifted Sigmoid"))
        self.label_5.setText(_translate("Form", "                                                               Contrast Enhancement"))
        self.DetectHumanEyePushButton.setText(_translate("Form", "Detect Human Eye"))
        self.DetectLines_PushButton.setText(_translate("Form", "Detect lines on highway"))
        self.label_6.setText(_translate("Form", "                                                                    Hough Transform"))
        self.NewImage.setText(_translate("Form", "NewImage"))
        self.label_7.setText(_translate("Form", "                                                                        Deblurring"))
        self.DeblurringPushButton.setText(_translate("Form", "Deblur"))
        self.label_8.setText(_translate("Form", "                                                        Count Objects and feature extract"))
        self.CountAndExtractButton.setText(_translate("Form", "Count And Extract"))
        self.tabWidgetOdev2.setTabText(self.tabWidgetOdev2.indexOf(self.tab_3), _translate("Form", "Ödev 1: Temel İşlevselliği Oluştur"))
        self.tabWidgetOdev2.setTabText(self.tabWidgetOdev2.indexOf(self.tab_4), _translate("Form", "Ödev 2: Filtre Uygulama"))
